name: Run Python Script Every 4 Hours

on:
  schedule:
    - cron: "* */4 * * *"   # every 4 hours
  workflow_dispatch:         # allow manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Run script
        run: python main.py
